### ISSUE TITLE
Hide bar and tabs on certain routes

### ISSUE THREAD

**Issue by gwendall** [meteoric/meteor-ionic#264]
Is there a built-in way to do that? For now, here is how i do:

``` javascript
Template.page.onCreated(function() {
  $('body').addClass('no-bar no-tabs');
});
Template.page.onDestroyed(function() {
  $('body').removeClass('no-bar no-tabs');
});
```

``` css
/* Using LESS */

body.no-bar .ionic-body {
  .bar-header { display: none; }
  .content.overflow-scroll { top: 0 !important; }
}
body.no-tabs .ionic-body {
  .tabs { display: none; }
  .content.overflow-scroll { bottom: 0 !important; }
}
```
