### ISSUE TITLE
Feature expose-aside-when for side-menu

### ISSUE THREAD

**Issue by miri-am** [meteoric/meteor-ionic#40]
In the readme it says "expose-aside-when (not sure this is needed)". I would be in need to this feature or is there already an easy way to implement something like this http://codepen.io/mhartington/pen/CvawB ?

**Comment by nickw** [comment]
Yeah I think we'd just need a resize listener (probably attached to `ionBody`) that manually opens the side menu once the viewport reaches a certain width.

**Comment by dancering** [comment]
This code in Template.nameXXXX.rendered will do it:

	Session.set('width', $('.snap-drawers').width());

	$(window).resize(function() {
		Session.set('width', $('.snap-drawers').width());
	});

	Tracker.autorun(function () {
		if (Session.get('width') >= 768) {
			$('.snap-content').css('-webkit-transform', 'translate3d(266px, 0px, 0px)');
		} else {
			$('.snap-content').css('-webkit-transform', 'translate3d(0px, 0px, 0px)');
		}
	});

**Comment by digilord** [comment]
One of the things you need to take into account is that the `.snap-content` slides over so any items that are to the right when the side menu is open are off screen.

I used
```
Template.layout.rendered = () ->
  Session.set('width', $('.snap-drawers').width())

  $(window).resize () ->
    Session.set('width', $('.snap-drawers').width())

  Tracker.autorun () ->
    if Session.get('width') >= 768
      $('.snap-content').css('-webkit-transform', 'translate3d(266px, 0px, 0px)')
      width = $('.snap-content').width() - 266
      $('.snap-content').css('width', "#{width}px")
      Session.set('_showWhenSideMenuOpen', false)
    else
      $('.snap-content').css('-webkit-transform', 'translate3d(0px, 0px, 0px)')
      $('.snap-content').css('width', "100%")
      Session.set('_showWhenSideMenuOpen', true)
```

If you have a right side menu things don't work very well. I built on the possible solution provided by @dancering. I would also very much like to see this feature in the package.

**Comment by dennisharrison** [comment]
@digilord & @dancering

Would also love to see this implemented. In Ionic when using this it renders the menu differently than the 'slide out' method in that it doesn't push the content over and the toggle no longer functions. For tablets and desktop this would be a great help. It's actually rendered to the left or right of the content instead of starting in the same space as the slide animation. 

I haven't spent enough time to understand how @nickw would really want to implement this in meteoric, but am willing to help.

**Comment by nickw** [comment]
Yeah, I'd love to see someone create a PR for this as I can definitely see how it would be useful. I don't have the time/need to do it myself right now, but may be able to in a few weeks. Here are some thoughts I have:

- It should definitely hide the corresponding "hamburger" button when the window is wide enough to expose the sidemenu.
- I think this could be implemented in either `ionBody` or `ionSidemenuContainer`
- It would be great if it could work on both the left and the right side
- Maybe it should disable `snap.js` altogether when wide enough and override the CSS, rather than trying to fight with `snap.js`

**Comment by dennisharrison** [comment]
@nikw I think it should disable snap.js of the element when this happens (and re-enable on resize) and then override the CSS.  I'll dig into this in particular when I'm working on visual stuff this week.

ionSidemenuContainer makes the most sense - right?

**Comment by nickw** [comment]
Yeah I think `ionSidemenuContainer` is best if possible. I'd prefer not to pollute `ionBody` more than necessary.

**Comment by personasio** [comment]
Quick question, how do i use the ionSideMenuContainer to create a slide menu?

**Comment by digilord** [comment]
Has there been any movement on this?

**Comment by mrn3** [comment]
I would love this feature too - is anyone working on it?

**Comment by digilord** [comment]
Is anyone sorting this out?

**Comment by nickw** [comment]
I don't think so. I probably won't work on it until I need it for an app.

**Comment by dennisharrison** [comment]
This should help anyone looking to get started on this:

This on your template .rendered() method.
```javascript
Tracker.autorun(function() {
  if (Session.get('width') >= 768) {
    IonSideMenu.snapper.disable();
    return Session.set('_showWhenSideMenuOpen', true);
  } else {
    IonSideMenu.snapper.enable();
    return Session.set('_showWhenSideMenuOpen', false);
  }
});
```



With similar CSS to this.
```css
@media (min-width: 770px) {
  .ionic-body {
    position: absolute;
    overflow: visible;
    max-width: 768px;
    margin-left: auto;
    margin-right: auto;
  }

  .snap-content {
    margin-left: 266px;
    max-width: 502px;
  }
  .snap-content .menu-toggle-icon {
    display: none;
  }

  .snap-drawer-left {
    position: absolute;
  }
  .snap-drawer-left .bar {
    width: 266px;
    right: auto;
    left: auto;
  }
}
@media (min-width: 1026px) {
  .ionic-body {
    max-width: 1024px;
  }

  .snap-content {
    max-width: 758px;
  }
}
```
